name: GraalVM smoke tests

on:
  pull_request: {}
permissions: {}
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]
        transport: [native, nio]
        exclude:
          # excludes native on Windows (there's none)
          - os: windows-2022
            transport: native
          # macOS - https://github.com/netty/netty/issues/9689
          - os: macos-13
            transport: native

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          path: reactor-netty
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          repository: netty-contrib/socks-proxy
          path: socks-proxy
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          repository: netty-contrib/codec-multipart
          path: codec-multipart
      - name: Set up GraalVM 17
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          distribution: 'graalvm'
          java-version: '17.0.12'
      - name: Build socks-proxy
        run: ./mvnw install -DskipTests=true "-Dnetty.version=5.0.0.Alpha6-SNAPSHOT"
        working-directory: ./socks-proxy
      - name: Build codec-multipart
        run: ./mvnw install -DskipTests=true "-Dnetty.version=5.0.0.Alpha6-SNAPSHOT"
        working-directory: ./codec-multipart
      - name: Build with Gradle
        run: ./gradlew :reactor-netty5-graalvm-smoke-tests:nativeTest --no-daemon -PforceTransport=${{ matrix.transport }}
        working-directory: ./reactor-netty